# Example Docker Compose File
# Please use this as a reference, don't use this verbatim in prod

version: '3'

services:
  statty:
    # Using a version tag is a good idea in production
    image: docker.pkg.github.com/lolpants/statty/statty
    restart: always
    networks:
      - internal
    depends_on:
      - redis
    ports:
      - 8080:3000
    volumes:
      # Mount config inside container
      - ./config.yaml:/app/config.yaml:ro
  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

networks:
  internal:
